version: '3.8'

services:
  backend:
    image: saipreetham7/restaurant-guide-backend:1.0
    container_name: restaurant-guide-backend
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000'
    restart: unless-stopped

  frontend:
    image: saipreetham7/restaurant-guide-frontend:1.0
    container_name: restaurant-guide-frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
    restart: unless-stopped

networks:
  default:
    name: restaurant-guide-network
